config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :essays do
    resources :comments
  end
  root "welcome#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :essay
end

app/models/essay.rb
class Essay < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum:5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @essay = Essay.find(params[:essay_id])
    @comment = @essay.comments.create(comment_params)
    redirect_to essay_path(@essay)
  end

  def destroy
    @essay = Essay.find(params[:essay_id])
    @comment = @essay.comments.find(params[:id])
    @comment.destroy
    redirect_to essay_path(@essay)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/essays_controller.rb
class EssaysController < ApplicationController
  def index
    @essays = Essay.all
  end

  def show
    @essay = Essay.find(params[:id])
  end

  def new
    @essay = Essay.new
  end

  def edit
    @essay = Essay.find(params[:id])
  end

  def create
    @essay = Essay.new(essay_params)

    if @essay.save
      redirect_to @essay
    else
      render 'new'
    end
  end

  def update
    @essay = Essay.find(params[:id])

    if @essay.update(essay_params)
      redirect_to @essay
    else
      render 'edit'
    end
  end

  def destroy
    @essay = Essay.find(params[:id])
    @essay.destroy

    redirect_to essays_path
  end

  private
    def essay_params
      params.require(:essay).permit(:title, :text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/essays_helper.rb
module EssaysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Delete comment', [comment.essay, comment], method: :delete, data: {confirm: 'Are you sure?'}  %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@essay, @essay.comments.build]) do |f|  %>
  <p>
    <%= f.label :commenter  %> <br>
    <%= f.text_field :commenter  %>
  </p>
  <p>
    <%= f.label :body  %> <br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit  %>
  </p>
<% end %>

app/views/essays/_form.html.erb
<%= form_for @essay do |f| %>

  <% if @essay.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@essay.errors.count, "error") %> prohibited
        this essay from being saved:
      </h2>
      <ul>
        <% @essay.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/essays/_header.html.erb
<div class="header">
  <h1><%= link_to 'EnglishLit', essays_path, {:style=>'color:#FFFFFF;', :class => "css_class"} %></h1>

</div>

app/views/essays/edit.html.erb
<%= render 'header' %>
<h1>Edit essay</h1>

<%= render 'form' %>

<%= link_to 'Back', essays_path %>

app/views/essays/index.html.erb
<%= render 'header' %>
<h1>Essays</h1>
  <%= link_to '<button>New essay</button>'.html_safe, new_essay_path %>
<table>
  <tr>
    <th>Title</th>
  </tr>
  <% @essays.each do |essay| %>
  <tr>
    <td><%= essay.title %></td>
    <td><%= link_to 'Show', essay_path(essay) %></td>
    <td><%= link_to 'Edit', edit_essay_path(essay) %></td>
    <td><%= link_to 'Delete', essay_path(essay), method: :delete, data: {confirm: 'Are you sure?'} %></td>
  </tr>
  <% end %>
</table>

app/views/essays/new.html.erb
<%= render 'header' %>
<h1>New Essay</h1>
<%= render 'form' %>

<%= link_to 'Back', essays_path %>

app/views/essays/show.html.erb
<%= render 'header' %>
<h1>
  Essay:
  <%= @essay.title %>
</h1>

<h2>Comments</h2>
<%= render @essay.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form'  %>

<%= link_to 'Edit', edit_essay_path(@essay) %> |
<%= link_to 'Back', essays_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnglishLit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="theme-color" content="#04caff" />
    <meta name="apple-mobile-web-app-status-bar-style" content="#04caff">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<%= render 'essays/header' %>
<h1>Hello, fellow student!</h1>
<%= link_to 'View essays', controller: 'essays' %>